/*1. Tome todas las funciones para operar sobre una lista simple enlazada y coloquelas en un archivo
llamado lsd.c y cree su archivo de cabecera correspondiente lse.h Luego cree un makefile que compile
lse.c como una librería estática. Finalmente agregue una regla en el makefile para compilar una función
main que demuestre el uso de las funciones de la lista simple enlazada linkeando la librería antes
creada.
*/